import { neon } from "@neondatabase/serverless"

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL environment variable is required for Neon")
}

const sql = neon(process.env.DATABASE_URL)

export interface Song {
  id?: number
  track_id: string
  track_name: string
  artist_name: string
  genre: string
  mood?: string
  tempo?: string
  energy?: number
  danceability?: number
  valence?: number
  popularity?: number
}

// 300 Song Dataset - Comprehensive music database
const songDatabase: Song[] = [
  // Pop Songs (20 songs)
  {
    track_id: "pop_001",
    track_name: "Blinding Lights",
    artist_name: "The Weeknd",
    genre: "pop",
    mood: "energetic",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.9,
    valence: 0.7,
    popularity: 95,
  },
  {
    track_id: "pop_002",
    track_name: "Shape of You",
    artist_name: "Ed Sheeran",
    genre: "pop",
    mood: "happy",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.8,
    popularity: 92,
  },
  {
    track_id: "pop_003",
    track_name: "Someone Like You",
    artist_name: "Adele",
    genre: "pop",
    mood: "sad",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.4,
    valence: 0.2,
    popularity: 88,
  },
  {
    track_id: "pop_004",
    track_name: "Perfect",
    artist_name: "Ed Sheeran",
    genre: "pop",
    mood: "romantic",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.5,
    valence: 0.8,
    popularity: 90,
  },
  {
    track_id: "pop_005",
    track_name: "Hello",
    artist_name: "Adele",
    genre: "pop",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.3,
    popularity: 89,
  },
  {
    track_id: "pop_006",
    track_name: "Uptown Funk",
    artist_name: "Bruno Mars",
    genre: "pop",
    mood: "happy",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.9,
    valence: 0.9,
    popularity: 91,
  },
  {
    track_id: "pop_007",
    track_name: "Can't Stop the Feeling",
    artist_name: "Justin Timberlake",
    genre: "pop",
    mood: "happy",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.8,
    valence: 0.9,
    popularity: 85,
  },
  {
    track_id: "pop_008",
    track_name: "Bad Guy",
    artist_name: "Billie Eilish",
    genre: "pop",
    mood: "dark",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.4,
    popularity: 87,
  },
  {
    track_id: "pop_009",
    track_name: "Watermelon Sugar",
    artist_name: "Harry Styles",
    genre: "pop",
    mood: "happy",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.8,
    popularity: 84,
  },
  {
    track_id: "pop_010",
    track_name: "Levitating",
    artist_name: "Dua Lipa",
    genre: "pop",
    mood: "energetic",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.9,
    valence: 0.8,
    popularity: 86,
  },
  {
    track_id: "pop_011",
    track_name: "Anti-Hero",
    artist_name: "Taylor Swift",
    genre: "pop",
    mood: "introspective",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.5,
    popularity: 93,
  },
  {
    track_id: "pop_012",
    track_name: "As It Was",
    artist_name: "Harry Styles",
    genre: "pop",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.6,
    popularity: 89,
  },
  {
    track_id: "pop_013",
    track_name: "Stay",
    artist_name: "The Kid LAROI & Justin Bieber",
    genre: "pop",
    mood: "emotional",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.6,
    popularity: 88,
  },
  {
    track_id: "pop_014",
    track_name: "Good 4 U",
    artist_name: "Olivia Rodrigo",
    genre: "pop",
    mood: "angry",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.7,
    valence: 0.4,
    popularity: 87,
  },
  {
    track_id: "pop_015",
    track_name: "Flowers",
    artist_name: "Miley Cyrus",
    genre: "pop",
    mood: "empowering",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.7,
    popularity: 91,
  },
  {
    track_id: "pop_016",
    track_name: "Cruel Summer",
    artist_name: "Taylor Swift",
    genre: "pop",
    mood: "bittersweet",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.8,
    valence: 0.6,
    popularity: 85,
  },
  {
    track_id: "pop_017",
    track_name: "Sunflower",
    artist_name: "Post Malone & Swae Lee",
    genre: "pop",
    mood: "chill",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.7,
    popularity: 86,
  },
  {
    track_id: "pop_018",
    track_name: "Circles",
    artist_name: "Post Malone",
    genre: "pop",
    mood: "melancholic",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.4,
    popularity: 84,
  },
  {
    track_id: "pop_019",
    track_name: "Don't Start Now",
    artist_name: "Dua Lipa",
    genre: "pop",
    mood: "confident",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.9,
    valence: 0.8,
    popularity: 87,
  },
  {
    track_id: "pop_020",
    track_name: "Senorita",
    artist_name: "Shawn Mendes & Camila Cabello",
    genre: "pop",
    mood: "romantic",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.8,
    popularity: 83,
  },

  // Rock Songs (20 songs)
  {
    track_id: "rock_001",
    track_name: "Bohemian Rhapsody",
    artist_name: "Queen",
    genre: "rock",
    mood: "dramatic",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.6,
    valence: 0.7,
    popularity: 96,
  },
  {
    track_id: "rock_002",
    track_name: "Hotel California",
    artist_name: "Eagles",
    genre: "rock",
    mood: "melancholic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.4,
    popularity: 94,
  },
  {
    track_id: "rock_003",
    track_name: "Stairway to Heaven",
    artist_name: "Led Zeppelin",
    genre: "rock",
    mood: "epic",
    tempo: "slow",
    energy: 0.7,
    danceability: 0.4,
    valence: 0.6,
    popularity: 95,
  },
  {
    track_id: "rock_004",
    track_name: "Sweet Child O' Mine",
    artist_name: "Guns N' Roses",
    genre: "rock",
    mood: "energetic",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.7,
    valence: 0.8,
    popularity: 92,
  },
  {
    track_id: "rock_005",
    track_name: "Thunderstruck",
    artist_name: "AC/DC",
    genre: "rock",
    mood: "energetic",
    tempo: "fast",
    energy: 0.95,
    danceability: 0.6,
    valence: 0.8,
    popularity: 90,
  },
  {
    track_id: "rock_006",
    track_name: "Smells Like Teen Spirit",
    artist_name: "Nirvana",
    genre: "rock",
    mood: "angry",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.7,
    valence: 0.3,
    popularity: 89,
  },
  {
    track_id: "rock_007",
    track_name: "Don't Stop Believin'",
    artist_name: "Journey",
    genre: "rock",
    mood: "uplifting",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.7,
    valence: 0.9,
    popularity: 91,
  },
  {
    track_id: "rock_008",
    track_name: "We Will Rock You",
    artist_name: "Queen",
    genre: "rock",
    mood: "powerful",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.6,
    valence: 0.8,
    popularity: 93,
  },
  {
    track_id: "rock_009",
    track_name: "Back in Black",
    artist_name: "AC/DC",
    genre: "rock",
    mood: "confident",
    tempo: "medium",
    energy: 0.9,
    danceability: 0.7,
    valence: 0.7,
    popularity: 88,
  },
  {
    track_id: "rock_010",
    track_name: "Livin' on a Prayer",
    artist_name: "Bon Jovi",
    genre: "rock",
    mood: "hopeful",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.8,
    valence: 0.8,
    popularity: 87,
  },
  {
    track_id: "rock_011",
    track_name: "Another Brick in the Wall",
    artist_name: "Pink Floyd",
    genre: "rock",
    mood: "rebellious",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.6,
    valence: 0.4,
    popularity: 86,
  },
  {
    track_id: "rock_012",
    track_name: "Free Bird",
    artist_name: "Lynyrd Skynyrd",
    genre: "rock",
    mood: "free",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.5,
    valence: 0.7,
    popularity: 85,
  },
  {
    track_id: "rock_013",
    track_name: "Imagine",
    artist_name: "John Lennon",
    genre: "rock",
    mood: "peaceful",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.4,
    valence: 0.6,
    popularity: 92,
  },
  {
    track_id: "rock_014",
    track_name: "Come As You Are",
    artist_name: "Nirvana",
    genre: "rock",
    mood: "introspective",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.5,
    popularity: 84,
  },
  {
    track_id: "rock_015",
    track_name: "Black",
    artist_name: "Pearl Jam",
    genre: "rock",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.5,
    danceability: 0.3,
    valence: 0.3,
    popularity: 83,
  },
  {
    track_id: "rock_016",
    track_name: "Enter Sandman",
    artist_name: "Metallica",
    genre: "rock",
    mood: "dark",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.6,
    valence: 0.4,
    popularity: 87,
  },
  {
    track_id: "rock_017",
    track_name: "Paranoid",
    artist_name: "Black Sabbath",
    genre: "rock",
    mood: "anxious",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.7,
    valence: 0.3,
    popularity: 82,
  },
  {
    track_id: "rock_018",
    track_name: "More Than a Feeling",
    artist_name: "Boston",
    genre: "rock",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.6,
    valence: 0.7,
    popularity: 81,
  },
  {
    track_id: "rock_019",
    track_name: "Tom Sawyer",
    artist_name: "Rush",
    genre: "rock",
    mood: "adventurous",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.6,
    valence: 0.7,
    popularity: 80,
  },
  {
    track_id: "rock_020",
    track_name: "Smoke on the Water",
    artist_name: "Deep Purple",
    genre: "rock",
    mood: "classic",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.6,
    valence: 0.6,
    popularity: 85,
  },

  // Hip-Hop Songs (20 songs)
  {
    track_id: "hiphop_001",
    track_name: "Lose Yourself",
    artist_name: "Eminem",
    genre: "hip-hop",
    mood: "motivational",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.7,
    valence: 0.6,
    popularity: 94,
  },
  {
    track_id: "hiphop_002",
    track_name: "HUMBLE.",
    artist_name: "Kendrick Lamar",
    genre: "hip-hop",
    mood: "confident",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.8,
    valence: 0.6,
    popularity: 89,
  },
  {
    track_id: "hiphop_003",
    track_name: "God's Plan",
    artist_name: "Drake",
    genre: "hip-hop",
    mood: "grateful",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.7,
    popularity: 91,
  },
  {
    track_id: "hiphop_004",
    track_name: "Sicko Mode",
    artist_name: "Travis Scott",
    genre: "hip-hop",
    mood: "hype",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.8,
    valence: 0.7,
    popularity: 88,
  },
  {
    track_id: "hiphop_005",
    track_name: "Old Town Road",
    artist_name: "Lil Nas X",
    genre: "hip-hop",
    mood: "fun",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.8,
    popularity: 92,
  },
  {
    track_id: "hiphop_006",
    track_name: "Hotline Bling",
    artist_name: "Drake",
    genre: "hip-hop",
    mood: "smooth",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.8,
    valence: 0.6,
    popularity: 87,
  },
  {
    track_id: "hiphop_007",
    track_name: "Stronger",
    artist_name: "Kanye West",
    genre: "hip-hop",
    mood: "empowering",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.8,
    valence: 0.8,
    popularity: 86,
  },
  {
    track_id: "hiphop_008",
    track_name: "In Da Club",
    artist_name: "50 Cent",
    genre: "hip-hop",
    mood: "party",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.9,
    valence: 0.8,
    popularity: 85,
  },
  {
    track_id: "hiphop_009",
    track_name: "Juicy",
    artist_name: "The Notorious B.I.G.",
    genre: "hip-hop",
    mood: "celebratory",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.8,
    popularity: 88,
  },
  {
    track_id: "hiphop_010",
    track_name: "Alright",
    artist_name: "Kendrick Lamar",
    genre: "hip-hop",
    mood: "hopeful",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.7,
    valence: 0.7,
    popularity: 84,
  },
  {
    track_id: "hiphop_011",
    track_name: "Money Trees",
    artist_name: "Kendrick Lamar",
    genre: "hip-hop",
    mood: "reflective",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.5,
    popularity: 82,
  },
  {
    track_id: "hiphop_012",
    track_name: "Stan",
    artist_name: "Eminem",
    genre: "hip-hop",
    mood: "dark",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.5,
    valence: 0.3,
    popularity: 86,
  },
  {
    track_id: "hiphop_013",
    track_name: "99 Problems",
    artist_name: "Jay-Z",
    genre: "hip-hop",
    mood: "defiant",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.7,
    valence: 0.6,
    popularity: 83,
  },
  {
    track_id: "hiphop_014",
    track_name: "Rap God",
    artist_name: "Eminem",
    genre: "hip-hop",
    mood: "intense",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.6,
    valence: 0.7,
    popularity: 87,
  },
  {
    track_id: "hiphop_015",
    track_name: "Swimming Pools",
    artist_name: "Kendrick Lamar",
    genre: "hip-hop",
    mood: "introspective",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.4,
    popularity: 81,
  },
  {
    track_id: "hiphop_016",
    track_name: "Mask Off",
    artist_name: "Future",
    genre: "hip-hop",
    mood: "atmospheric",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.6,
    popularity: 85,
  },
  {
    track_id: "hiphop_017",
    track_name: "XO Tour Llif3",
    artist_name: "Lil Uzi Vert",
    genre: "hip-hop",
    mood: "emotional",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.4,
    popularity: 84,
  },
  {
    track_id: "hiphop_018",
    track_name: "LOYALTY.",
    artist_name: "Kendrick Lamar ft. Rihanna",
    genre: "hip-hop",
    mood: "smooth",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.8,
    valence: 0.7,
    popularity: 80,
  },
  {
    track_id: "hiphop_019",
    track_name: "Congratulations",
    artist_name: "Post Malone",
    genre: "hip-hop",
    mood: "celebratory",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.8,
    popularity: 86,
  },
  {
    track_id: "hiphop_020",
    track_name: "Life is Good",
    artist_name: "Future ft. Drake",
    genre: "hip-hop",
    mood: "content",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.8,
    valence: 0.7,
    popularity: 83,
  },

  // R&B Songs (20 songs)
  {
    track_id: "rnb_001",
    track_name: "Blurred Lines",
    artist_name: "Robin Thicke",
    genre: "r&b",
    mood: "seductive",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.8,
    popularity: 87,
  },
  {
    track_id: "rnb_002",
    track_name: "Crazy in Love",
    artist_name: "Beyoncé",
    genre: "r&b",
    mood: "passionate",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.9,
    valence: 0.9,
    popularity: 90,
  },
  {
    track_id: "rnb_003",
    track_name: "Adorn",
    artist_name: "Miguel",
    genre: "r&b",
    mood: "romantic",
    tempo: "slow",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.8,
    popularity: 82,
  },
  {
    track_id: "rnb_004",
    track_name: "Best Part",
    artist_name: "Daniel Caesar ft. H.E.R.",
    genre: "r&b",
    mood: "loving",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.5,
    valence: 0.9,
    popularity: 85,
  },
  {
    track_id: "rnb_005",
    track_name: "Golden",
    artist_name: "Jill Scott",
    genre: "r&b",
    mood: "uplifting",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.9,
    popularity: 78,
  },
  {
    track_id: "rnb_006",
    track_name: "No Scrubs",
    artist_name: "TLC",
    genre: "r&b",
    mood: "empowering",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.7,
    popularity: 84,
  },
  {
    track_id: "rnb_007",
    track_name: "I Want It That Way",
    artist_name: "Backstreet Boys",
    genre: "r&b",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.7,
    popularity: 89,
  },
  {
    track_id: "rnb_008",
    track_name: "My Girl",
    artist_name: "The Temptations",
    genre: "r&b",
    mood: "joyful",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.9,
    popularity: 86,
  },
  {
    track_id: "rnb_009",
    track_name: "Superstition",
    artist_name: "Stevie Wonder",
    genre: "r&b",
    mood: "groovy",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.9,
    valence: 0.8,
    popularity: 88,
  },
  {
    track_id: "rnb_010",
    track_name: "Respect",
    artist_name: "Aretha Franklin",
    genre: "r&b",
    mood: "empowering",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.7,
    valence: 0.8,
    popularity: 91,
  },
  {
    track_id: "rnb_011",
    track_name: "What's Going On",
    artist_name: "Marvin Gaye",
    genre: "r&b",
    mood: "contemplative",
    tempo: "slow",
    energy: 0.5,
    danceability: 0.4,
    valence: 0.5,
    popularity: 87,
  },
  {
    track_id: "rnb_012",
    track_name: "I Will Always Love You",
    artist_name: "Whitney Houston",
    genre: "r&b",
    mood: "emotional",
    tempo: "slow",
    energy: 0.6,
    danceability: 0.3,
    valence: 0.6,
    popularity: 93,
  },
  {
    track_id: "rnb_013",
    track_name: "Isn't She Lovely",
    artist_name: "Stevie Wonder",
    genre: "r&b",
    mood: "joyful",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.8,
    valence: 0.9,
    popularity: 85,
  },
  {
    track_id: "rnb_014",
    track_name: "Let's Stay Together",
    artist_name: "Al Green",
    genre: "r&b",
    mood: "romantic",
    tempo: "slow",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.8,
    popularity: 83,
  },
  {
    track_id: "rnb_015",
    track_name: "I Heard It Through the Grapevine",
    artist_name: "Marvin Gaye",
    genre: "r&b",
    mood: "soulful",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.5,
    popularity: 82,
  },
  {
    track_id: "rnb_016",
    track_name: "Sexual Healing",
    artist_name: "Marvin Gaye",
    genre: "r&b",
    mood: "sensual",
    tempo: "slow",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.7,
    popularity: 81,
  },
  {
    track_id: "rnb_017",
    track_name: "End of the Road",
    artist_name: "Boyz II Men",
    genre: "r&b",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.3,
    popularity: 84,
  },
  {
    track_id: "rnb_018",
    track_name: "I'll Make Love to You",
    artist_name: "Boyz II Men",
    genre: "r&b",
    mood: "romantic",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.4,
    valence: 0.8,
    popularity: 86,
  },
  {
    track_id: "rnb_019",
    track_name: "Waterfalls",
    artist_name: "TLC",
    genre: "r&b",
    mood: "cautionary",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.5,
    popularity: 88,
  },
  {
    track_id: "rnb_020",
    track_name: "That's What Friends Are For",
    artist_name: "Dionne Warwick",
    genre: "r&b",
    mood: "supportive",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.8,
    popularity: 80,
  },

  // Electronic/EDM Songs (20 songs)
  {
    track_id: "edm_001",
    track_name: "Titanium",
    artist_name: "David Guetta ft. Sia",
    genre: "electronic",
    mood: "empowering",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.9,
    valence: 0.8,
    popularity: 89,
  },
  {
    track_id: "edm_002",
    track_name: "Levels",
    artist_name: "Avicii",
    genre: "electronic",
    mood: "euphoric",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.9,
    valence: 0.9,
    popularity: 87,
  },
  {
    track_id: "edm_003",
    track_name: "Clarity",
    artist_name: "Zedd ft. Foxes",
    genre: "electronic",
    mood: "emotional",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.8,
    valence: 0.6,
    popularity: 85,
  },
  {
    track_id: "edm_004",
    track_name: "Animals",
    artist_name: "Martin Garrix",
    genre: "electronic",
    mood: "intense",
    tempo: "fast",
    energy: 0.95,
    danceability: 0.9,
    valence: 0.7,
    popularity: 84,
  },
  {
    track_id: "edm_005",
    track_name: "Wake Me Up",
    artist_name: "Avicii",
    genre: "electronic",
    mood: "uplifting",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.8,
    valence: 0.8,
    popularity: 88,
  },
  {
    track_id: "edm_006",
    track_name: "Bangarang",
    artist_name: "Skrillex",
    genre: "electronic",
    mood: "aggressive",
    tempo: "fast",
    energy: 0.95,
    danceability: 0.8,
    valence: 0.7,
    popularity: 82,
  },
  {
    track_id: "edm_007",
    track_name: "Scary Monsters and Nice Sprites",
    artist_name: "Skrillex",
    genre: "electronic",
    mood: "chaotic",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.8,
    valence: 0.6,
    popularity: 81,
  },
  {
    track_id: "edm_008",
    track_name: "Strobe",
    artist_name: "Deadmau5",
    genre: "electronic",
    mood: "atmospheric",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.6,
    popularity: 79,
  },
  {
    track_id: "edm_009",
    track_name: "One More Time",
    artist_name: "Daft Punk",
    genre: "electronic",
    mood: "celebratory",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.9,
    valence: 0.9,
    popularity: 86,
  },
  {
    track_id: "edm_010",
    track_name: "Around the World",
    artist_name: "Daft Punk",
    genre: "electronic",
    mood: "hypnotic",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.9,
    valence: 0.7,
    popularity: 83,
  },
  {
    track_id: "edm_011",
    track_name: "Sandstorm",
    artist_name: "Darude",
    genre: "electronic",
    mood: "energetic",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.8,
    valence: 0.7,
    popularity: 85,
  },
  {
    track_id: "edm_012",
    track_name: "Midnight City",
    artist_name: "M83",
    genre: "electronic",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.7,
    popularity: 80,
  },
  {
    track_id: "edm_013",
    track_name: "Lean On",
    artist_name: "Major Lazer",
    genre: "electronic",
    mood: "tropical",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.8,
    popularity: 87,
  },
  {
    track_id: "edm_014",
    track_name: "Closer",
    artist_name: "The Chainsmokers",
    genre: "electronic",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.6,
    popularity: 90,
  },
  {
    track_id: "edm_015",
    track_name: "Don't You (Forget About Me)",
    artist_name: "Simple Minds",
    genre: "electronic",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.7,
    popularity: 84,
  },
  {
    track_id: "edm_016",
    track_name: "Blue Monday",
    artist_name: "New Order",
    genre: "electronic",
    mood: "melancholic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.8,
    valence: 0.4,
    popularity: 82,
  },
  {
    track_id: "edm_017",
    track_name: "Enjoy the Silence",
    artist_name: "Depeche Mode",
    genre: "electronic",
    mood: "contemplative",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.5,
    popularity: 81,
  },
  {
    track_id: "edm_018",
    track_name: "Personal Jesus",
    artist_name: "Depeche Mode",
    genre: "electronic",
    mood: "dark",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.5,
    popularity: 80,
  },
  {
    track_id: "edm_019",
    track_name: "Sweet Dreams",
    artist_name: "Eurythmics",
    genre: "electronic",
    mood: "mysterious",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.5,
    popularity: 83,
  },
  {
    track_id: "edm_020",
    track_name: "Tainted Love",
    artist_name: "Soft Cell",
    genre: "electronic",
    mood: "dark",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.8,
    valence: 0.4,
    popularity: 78,
  },

  // Country Songs (20 songs)
  {
    track_id: "country_001",
    track_name: "Friends in Low Places",
    artist_name: "Garth Brooks",
    genre: "country",
    mood: "friendly",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.8,
    popularity: 88,
  },
  {
    track_id: "country_002",
    track_name: "Sweet Caroline",
    artist_name: "Neil Diamond",
    genre: "country",
    mood: "joyful",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.9,
    popularity: 89,
  },
  {
    track_id: "country_003",
    track_name: "Take Me Home, Country Roads",
    artist_name: "John Denver",
    genre: "country",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.8,
    popularity: 87,
  },
  {
    track_id: "country_004",
    track_name: "Jolene",
    artist_name: "Dolly Parton",
    genre: "country",
    mood: "pleading",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.4,
    popularity: 85,
  },
  {
    track_id: "country_005",
    track_name: "Ring of Fire",
    artist_name: "Johnny Cash",
    genre: "country",
    mood: "passionate",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.6,
    valence: 0.7,
    popularity: 86,
  },
  {
    track_id: "country_006",
    track_name: "Mammas Don't Let Your Babies Grow Up to Be Cowboys",
    artist_name: "Willie Nelson",
    genre: "country",
    mood: "advisory",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.5,
    valence: 0.6,
    popularity: 82,
  },
  {
    track_id: "country_007",
    track_name: "Coal Miner's Daughter",
    artist_name: "Loretta Lynn",
    genre: "country",
    mood: "proud",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.7,
    popularity: 81,
  },
  {
    track_id: "country_008",
    track_name: "He Stopped Loving Her Today",
    artist_name: "George Jones",
    genre: "country",
    mood: "tragic",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.3,
    valence: 0.2,
    popularity: 83,
  },
  {
    track_id: "country_009",
    track_name: "Crazy",
    artist_name: "Patsy Cline",
    genre: "country",
    mood: "heartbroken",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.4,
    valence: 0.3,
    popularity: 84,
  },
  {
    track_id: "country_010",
    track_name: "I Walk the Line",
    artist_name: "Johnny Cash",
    genre: "country",
    mood: "devoted",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.5,
    valence: 0.7,
    popularity: 85,
  },
  {
    track_id: "country_011",
    track_name: "Blue Eyes Crying in the Rain",
    artist_name: "Willie Nelson",
    genre: "country",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.3,
    valence: 0.3,
    popularity: 80,
  },
  {
    track_id: "country_012",
    track_name: "Whiskey River",
    artist_name: "Willie Nelson",
    genre: "country",
    mood: "drowning sorrows",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.5,
    valence: 0.4,
    popularity: 79,
  },
  {
    track_id: "country_013",
    track_name: "Stand By Your Man",
    artist_name: "Tammy Wynette",
    genre: "country",
    mood: "loyal",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.5,
    valence: 0.6,
    popularity: 82,
  },
  {
    track_id: "country_014",
    track_name: "The Gambler",
    artist_name: "Kenny Rogers",
    genre: "country",
    mood: "wise",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.5,
    valence: 0.6,
    popularity: 83,
  },
  {
    track_id: "country_015",
    track_name: "On the Road Again",
    artist_name: "Willie Nelson",
    genre: "country",
    mood: "adventurous",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.8,
    popularity: 81,
  },
  {
    track_id: "country_016",
    track_name: "Wagon Wheel",
    artist_name: "Old Crow Medicine Show",
    genre: "country",
    mood: "wandering",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.7,
    popularity: 78,
  },
  {
    track_id: "country_017",
    track_name: "Tennessee Whiskey",
    artist_name: "Chris Stapleton",
    genre: "country",
    mood: "smooth",
    tempo: "slow",
    energy: 0.5,
    danceability: 0.5,
    valence: 0.7,
    popularity: 84,
  },
  {
    track_id: "country_018",
    track_name: "Body Like a Back Road",
    artist_name: "Sam Hunt",
    genre: "country",
    mood: "romantic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.8,
    popularity: 82,
  },
  {
    track_id: "country_019",
    track_name: "Cruise",
    artist_name: "Florida Georgia Line",
    genre: "country",
    mood: "carefree",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.8,
    popularity: 80,
  },
  {
    track_id: "country_020",
    track_name: "Need You Now",
    artist_name: "Lady Antebellum",
    genre: "country",
    mood: "longing",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.5,
    valence: 0.4,
    popularity: 85,
  },

  // Jazz Songs (20 songs)
  {
    track_id: "jazz_001",
    track_name: "Take Five",
    artist_name: "Dave Brubeck",
    genre: "jazz",
    mood: "sophisticated",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.7,
    popularity: 82,
  },
  {
    track_id: "jazz_002",
    track_name: "What a Wonderful World",
    artist_name: "Louis Armstrong",
    genre: "jazz",
    mood: "optimistic",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.4,
    valence: 0.9,
    popularity: 88,
  },
  {
    track_id: "jazz_003",
    track_name: "Fly Me to the Moon",
    artist_name: "Frank Sinatra",
    genre: "jazz",
    mood: "romantic",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.8,
    popularity: 86,
  },
  {
    track_id: "jazz_004",
    track_name: "Summertime",
    artist_name: "Ella Fitzgerald",
    genre: "jazz",
    mood: "dreamy",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.4,
    valence: 0.6,
    popularity: 84,
  },
  {
    track_id: "jazz_005",
    track_name: "Blue Moon",
    artist_name: "Billie Holiday",
    genre: "jazz",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.3,
    valence: 0.4,
    popularity: 83,
  },
  {
    track_id: "jazz_006",
    track_name: "Autumn Leaves",
    artist_name: "Nat King Cole",
    genre: "jazz",
    mood: "nostalgic",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.4,
    valence: 0.5,
    popularity: 81,
  },
  {
    track_id: "jazz_007",
    track_name: "All of Me",
    artist_name: "Billie Holiday",
    genre: "jazz",
    mood: "devoted",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.4,
    valence: 0.7,
    popularity: 82,
  },
  {
    track_id: "jazz_008",
    track_name: "Mack the Knife",
    artist_name: "Bobby Darin",
    genre: "jazz",
    mood: "playful",
    tempo: "fast",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.8,
    popularity: 80,
  },
  {
    track_id: "jazz_009",
    track_name: "The Way You Look Tonight",
    artist_name: "Frank Sinatra",
    genre: "jazz",
    mood: "romantic",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.8,
    popularity: 85,
  },
  {
    track_id: "jazz_010",
    track_name: "Cheek to Cheek",
    artist_name: "Ella Fitzgerald",
    genre: "jazz",
    mood: "intimate",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.7,
    valence: 0.8,
    popularity: 79,
  },
  {
    track_id: "jazz_011",
    track_name: "In a Sentimental Mood",
    artist_name: "Duke Ellington",
    genre: "jazz",
    mood: "sentimental",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.4,
    valence: 0.6,
    popularity: 78,
  },
  {
    track_id: "jazz_012",
    track_name: "Round Midnight",
    artist_name: "Thelonious Monk",
    genre: "jazz",
    mood: "contemplative",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.3,
    valence: 0.4,
    popularity: 77,
  },
  {
    track_id: "jazz_013",
    track_name: "So What",
    artist_name: "Miles Davis",
    genre: "jazz",
    mood: "cool",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.4,
    valence: 0.6,
    popularity: 80,
  },
  {
    track_id: "jazz_014",
    track_name: "A Love Supreme",
    artist_name: "John Coltrane",
    genre: "jazz",
    mood: "spiritual",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.3,
    valence: 0.7,
    popularity: 76,
  },
  {
    track_id: "jazz_015",
    track_name: "Giant Steps",
    artist_name: "John Coltrane",
    genre: "jazz",
    mood: "complex",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.4,
    valence: 0.6,
    popularity: 75,
  },
  {
    track_id: "jazz_016",
    track_name: "Birdland",
    artist_name: "Weather Report",
    genre: "jazz",
    mood: "energetic",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.6,
    valence: 0.8,
    popularity: 74,
  },
  {
    track_id: "jazz_017",
    track_name: "Spain",
    artist_name: "Chick Corea",
    genre: "jazz",
    mood: "passionate",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.5,
    valence: 0.7,
    popularity: 73,
  },
  {
    track_id: "jazz_018",
    track_name: "Cantaloupe Island",
    artist_name: "Herbie Hancock",
    genre: "jazz",
    mood: "groovy",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.7,
    popularity: 76,
  },
  {
    track_id: "jazz_019",
    track_name: "Maiden Voyage",
    artist_name: "Herbie Hancock",
    genre: "jazz",
    mood: "exploratory",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.4,
    valence: 0.6,
    popularity: 75,
  },
  {
    track_id: "jazz_020",
    track_name: "Chameleon",
    artist_name: "Herbie Hancock",
    genre: "jazz",
    mood: "funky",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.7,
    popularity: 77,
  },

  // Folk Songs (20 songs)
  {
    track_id: "folk_001",
    track_name: "Blowin' in the Wind",
    artist_name: "Bob Dylan",
    genre: "folk",
    mood: "questioning",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.4,
    valence: 0.5,
    popularity: 87,
  },
  {
    track_id: "folk_002",
    track_name: "The Times They Are a-Changin'",
    artist_name: "Bob Dylan",
    genre: "folk",
    mood: "revolutionary",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.4,
    valence: 0.6,
    popularity: 85,
  },
  {
    track_id: "folk_003",
    track_name: "Both Sides Now",
    artist_name: "Joni Mitchell",
    genre: "folk",
    mood: "reflective",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.5,
    popularity: 83,
  },
  {
    track_id: "folk_004",
    track_name: "Big Yellow Taxi",
    artist_name: "Joni Mitchell",
    genre: "folk",
    mood: "environmental",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.5,
    popularity: 81,
  },
  {
    track_id: "folk_005",
    track_name: "Fire and Rain",
    artist_name: "James Taylor",
    genre: "folk",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.4,
    popularity: 84,
  },
  {
    track_id: "folk_006",
    track_name: "Vincent (Starry Starry Night)",
    artist_name: "Don McLean",
    genre: "folk",
    mood: "tribute",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.3,
    valence: 0.5,
    popularity: 82,
  },
  {
    track_id: "folk_007",
    track_name: "American Pie",
    artist_name: "Don McLean",
    genre: "folk",
    mood: "nostalgic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.6,
    popularity: 88,
  },
  {
    track_id: "folk_008",
    track_name: "The Sound of Silence",
    artist_name: "Simon & Garfunkel",
    genre: "folk",
    mood: "contemplative",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.4,
    popularity: 86,
  },
  {
    track_id: "folk_009",
    track_name: "Bridge Over Troubled Water",
    artist_name: "Simon & Garfunkel",
    genre: "folk",
    mood: "comforting",
    tempo: "slow",
    energy: 0.5,
    danceability: 0.3,
    valence: 0.7,
    popularity: 89,
  },
  {
    track_id: "folk_010",
    track_name: "Mrs. Robinson",
    artist_name: "Simon & Garfunkel",
    genre: "folk",
    mood: "playful",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.7,
    popularity: 84,
  },
  {
    track_id: "folk_011",
    track_name: "Suzanne",
    artist_name: "Leonard Cohen",
    genre: "folk",
    mood: "mystical",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.3,
    valence: 0.5,
    popularity: 80,
  },
  {
    track_id: "folk_012",
    track_name: "Hallelujah",
    artist_name: "Leonard Cohen",
    genre: "folk",
    mood: "spiritual",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.6,
    popularity: 90,
  },
  {
    track_id: "folk_013",
    track_name: "Fast Car",
    artist_name: "Tracy Chapman",
    genre: "folk",
    mood: "hopeful",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.4,
    valence: 0.6,
    popularity: 85,
  },
  {
    track_id: "folk_014",
    track_name: "Landslide",
    artist_name: "Fleetwood Mac",
    genre: "folk",
    mood: "introspective",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.5,
    popularity: 87,
  },
  {
    track_id: "folk_015",
    track_name: "Mad World",
    artist_name: "Gary Jules",
    genre: "folk",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.2,
    danceability: 0.2,
    valence: 0.2,
    popularity: 79,
  },
  {
    track_id: "folk_016",
    track_name: "Hurt",
    artist_name: "Johnny Cash",
    genre: "folk",
    mood: "regretful",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.2,
    valence: 0.2,
    popularity: 83,
  },
  {
    track_id: "folk_017",
    track_name: "The Man in Black",
    artist_name: "Johnny Cash",
    genre: "folk",
    mood: "defiant",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.4,
    valence: 0.5,
    popularity: 81,
  },
  {
    track_id: "folk_018",
    track_name: "Blackbird",
    artist_name: "The Beatles",
    genre: "folk",
    mood: "hopeful",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.7,
    popularity: 86,
  },
  {
    track_id: "folk_019",
    track_name: "Here Comes the Sun",
    artist_name: "The Beatles",
    genre: "folk",
    mood: "optimistic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.9,
    popularity: 88,
  },
  {
    track_id: "folk_020",
    track_name: "Norwegian Wood",
    artist_name: "The Beatles",
    genre: "folk",
    mood: "mysterious",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.4,
    valence: 0.6,
    popularity: 82,
  },

  // Reggae Songs (20 songs)
  {
    track_id: "reggae_001",
    track_name: "No Woman No Cry",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "comforting",
    tempo: "slow",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.7,
    popularity: 89,
  },
  {
    track_id: "reggae_002",
    track_name: "Three Little Birds",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "reassuring",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.9,
    popularity: 87,
  },
  {
    track_id: "reggae_003",
    track_name: "One Love",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "unifying",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.9,
    popularity: 88,
  },
  {
    track_id: "reggae_004",
    track_name: "Redemption Song",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "liberating",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.4,
    valence: 0.7,
    popularity: 86,
  },
  {
    track_id: "reggae_005",
    track_name: "I Shot the Sheriff",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "defiant",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.5,
    popularity: 85,
  },
  {
    track_id: "reggae_006",
    track_name: "Buffalo Soldier",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "historical",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.6,
    popularity: 84,
  },
  {
    track_id: "reggae_007",
    track_name: "Get Up, Stand Up",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "activist",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.7,
    popularity: 83,
  },
  {
    track_id: "reggae_008",
    track_name: "Could You Be Loved",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "questioning",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.7,
    popularity: 82,
  },
  {
    track_id: "reggae_009",
    track_name: "Is This Love",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "romantic",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.8,
    popularity: 85,
  },
  {
    track_id: "reggae_010",
    track_name: "Jamming",
    artist_name: "Bob Marley",
    genre: "reggae",
    mood: "celebratory",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.8,
    valence: 0.8,
    popularity: 81,
  },
  {
    track_id: "reggae_011",
    track_name: "Red Red Wine",
    artist_name: "UB40",
    genre: "reggae",
    mood: "drowning sorrows",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.4,
    popularity: 80,
  },
  {
    track_id: "reggae_012",
    track_name: "Electric Avenue",
    artist_name: "Eddy Grant",
    genre: "reggae",
    mood: "energetic",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.8,
    valence: 0.7,
    popularity: 79,
  },
  {
    track_id: "reggae_013",
    track_name: "The Harder They Come",
    artist_name: "Jimmy Cliff",
    genre: "reggae",
    mood: "determined",
    tempo: "medium",
    energy: 0.7,
    danceability: 0.7,
    valence: 0.6,
    popularity: 78,
  },
  {
    track_id: "reggae_014",
    track_name: "Many Rivers to Cross",
    artist_name: "Jimmy Cliff",
    genre: "reggae",
    mood: "struggling",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.4,
    valence: 0.4,
    popularity: 77,
  },
  {
    track_id: "reggae_015",
    track_name: "54-46 That's My Number",
    artist_name: "Toots and the Maytals",
    genre: "reggae",
    mood: "defiant",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.5,
    popularity: 76,
  },
  {
    track_id: "reggae_016",
    track_name: "Pressure Drop",
    artist_name: "Toots and the Maytals",
    genre: "reggae",
    mood: "warning",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.5,
    popularity: 75,
  },
  {
    track_id: "reggae_017",
    track_name: "The Israelites",
    artist_name: "Desmond Dekker",
    genre: "reggae",
    mood: "struggling",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.4,
    popularity: 74,
  },
  {
    track_id: "reggae_018",
    track_name: "Police and Thieves",
    artist_name: "Junior Murvin",
    genre: "reggae",
    mood: "social commentary",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.6,
    valence: 0.4,
    popularity: 73,
  },
  {
    track_id: "reggae_019",
    track_name: "Marcus Garvey",
    artist_name: "Burning Spear",
    genre: "reggae",
    mood: "revolutionary",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.6,
    popularity: 72,
  },
  {
    track_id: "reggae_020",
    track_name: "Legalize It",
    artist_name: "Peter Tosh",
    genre: "reggae",
    mood: "activist",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.6,
    valence: 0.6,
    popularity: 74,
  },

  // Classical Songs (20 songs)
  {
    track_id: "classical_001",
    track_name: "Für Elise",
    artist_name: "Ludwig van Beethoven",
    genre: "classical",
    mood: "elegant",
    tempo: "medium",
    energy: 0.5,
    danceability: 0.3,
    valence: 0.7,
    popularity: 85,
  },
  {
    track_id: "classical_002",
    track_name: "Symphony No. 9",
    artist_name: "Ludwig van Beethoven",
    genre: "classical",
    mood: "triumphant",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.3,
    valence: 0.9,
    popularity: 88,
  },
  {
    track_id: "classical_003",
    track_name: "Eine kleine Nachtmusik",
    artist_name: "Wolfgang Amadeus Mozart",
    genre: "classical",
    mood: "cheerful",
    tempo: "fast",
    energy: 0.7,
    danceability: 0.4,
    valence: 0.8,
    popularity: 84,
  },
  {
    track_id: "classical_004",
    track_name: "Requiem",
    artist_name: "Wolfgang Amadeus Mozart",
    genre: "classical",
    mood: "solemn",
    tempo: "slow",
    energy: 0.6,
    danceability: 0.2,
    valence: 0.3,
    popularity: 82,
  },
  {
    track_id: "classical_005",
    track_name: "The Four Seasons",
    artist_name: "Antonio Vivaldi",
    genre: "classical",
    mood: "seasonal",
    tempo: "fast",
    energy: 0.8,
    danceability: 0.4,
    valence: 0.8,
    popularity: 86,
  },
  {
    track_id: "classical_006",
    track_name: "Canon in D",
    artist_name: "Johann Pachelbel",
    genre: "classical",
    mood: "peaceful",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.3,
    valence: 0.7,
    popularity: 83,
  },
  {
    track_id: "classical_007",
    track_name: "Ave Maria",
    artist_name: "Franz Schubert",
    genre: "classical",
    mood: "spiritual",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.2,
    valence: 0.8,
    popularity: 81,
  },
  {
    track_id: "classical_008",
    track_name: "Moonlight Sonata",
    artist_name: "Ludwig van Beethoven",
    genre: "classical",
    mood: "melancholic",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.2,
    valence: 0.4,
    popularity: 87,
  },
  {
    track_id: "classical_009",
    track_name: "Swan Lake",
    artist_name: "Pyotr Ilyich Tchaikovsky",
    genre: "classical",
    mood: "graceful",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.5,
    valence: 0.7,
    popularity: 80,
  },
  {
    track_id: "classical_010",
    track_name: "1812 Overture",
    artist_name: "Pyotr Ilyich Tchaikovsky",
    genre: "classical",
    mood: "patriotic",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.3,
    valence: 0.8,
    popularity: 79,
  },
  {
    track_id: "classical_011",
    track_name: "Clair de Lune",
    artist_name: "Claude Debussy",
    genre: "classical",
    mood: "dreamy",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.2,
    valence: 0.6,
    popularity: 78,
  },
  {
    track_id: "classical_012",
    track_name: "Bolero",
    artist_name: "Maurice Ravel",
    genre: "classical",
    mood: "building",
    tempo: "slow",
    energy: 0.7,
    danceability: 0.4,
    valence: 0.6,
    popularity: 77,
  },
  {
    track_id: "classical_013",
    track_name: "The Blue Danube",
    artist_name: "Johann Strauss II",
    genre: "classical",
    mood: "waltzing",
    tempo: "medium",
    energy: 0.6,
    danceability: 0.7,
    valence: 0.8,
    popularity: 76,
  },
  {
    track_id: "classical_014",
    track_name: "William Tell Overture",
    artist_name: "Gioachino Rossini",
    genre: "classical",
    mood: "adventurous",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.4,
    valence: 0.8,
    popularity: 75,
  },
  {
    track_id: "classical_015",
    track_name: "Ride of the Valkyries",
    artist_name: "Richard Wagner",
    genre: "classical",
    mood: "epic",
    tempo: "fast",
    energy: 0.9,
    danceability: 0.3,
    valence: 0.7,
    popularity: 74,
  },
  {
    track_id: "classical_016",
    track_name: "Gymnopédie No. 1",
    artist_name: "Erik Satie",
    genre: "classical",
    mood: "minimalist",
    tempo: "slow",
    energy: 0.2,
    danceability: 0.2,
    valence: 0.5,
    popularity: 73,
  },
  {
    track_id: "classical_017",
    track_name: "Prelude in C Major",
    artist_name: "Johann Sebastian Bach",
    genre: "classical",
    mood: "meditative",
    tempo: "slow",
    energy: 0.4,
    danceability: 0.2,
    valence: 0.6,
    popularity: 76,
  },
  {
    track_id: "classical_018",
    track_name: "Brandenburg Concerto No. 3",
    artist_name: "Johann Sebastian Bach",
    genre: "classical",
    mood: "baroque",
    tempo: "fast",
    energy: 0.7,
    danceability: 0.3,
    valence: 0.7,
    popularity: 75,
  },
  {
    track_id: "classical_019",
    track_name: "Air on the G String",
    artist_name: "Johann Sebastian Bach",
    genre: "classical",
    mood: "serene",
    tempo: "slow",
    energy: 0.3,
    danceability: 0.2,
    valence: 0.7,
    popularity: 77,
  },
  {
    track_id: "classical_020",
    track_name: "Toccata and Fugue in D minor",
    artist_name: "Johann Sebastian Bach",
    genre: "classical",
    mood: "dramatic",
    tempo: "medium",
    energy: 0.8,
    danceability: 0.2,
    valence: 0.5,
    popularity: 78,
  },
]

async function executeWithFallback<T>(operation: () => Promise<T>, fallback: T): Promise<T> {
  try {
    const timeoutPromise = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("Database timeout")), 5000),
    )
    return await Promise.race([operation(), timeoutPromise])
  } catch (error) {
    console.log("⚠️ Database unavailable, using fallback data")
    return fallback
  }
}

export async function storeSongMetadata(song: Song): Promise<void> {
  try {
    await sql`
      INSERT INTO songs (
        track_id, track_name, artist_name, genre, mood, tempo,
        energy, danceability, valence, popularity
      ) VALUES (
        ${song.track_id}, ${song.track_name}, ${song.artist_name}, 
        ${song.genre}, ${song.mood || null}, ${song.tempo || null},
        ${song.energy || null}, ${song.danceability || null}, ${song.valence || null},
        ${song.popularity || null}
      )
      ON CONFLICT (track_id) 
      DO UPDATE SET
        track_name = EXCLUDED.track_name,
        artist_name = EXCLUDED.artist_name,
        genre = EXCLUDED.genre,
        mood = EXCLUDED.mood,
        tempo = EXCLUDED.tempo,
        energy = EXCLUDED.energy,
        danceability = EXCLUDED.danceability,
        valence = EXCLUDED.valence,
        popularity = EXCLUDED.popularity,
        updated_at = CURRENT_TIMESTAMP
    `
    console.log(`✅ Stored song metadata: ${song.track_name}`)
  } catch (error) {
    console.log(`⚠️ Database store failed for ${song.track_name}, continuing...`)
  }
}

export async function getSongsByGenre(genre: string, limit = 10): Promise<Song[]> {
  return executeWithFallback(
    async () => {
      const result = await sql`
        SELECT * FROM songs 
        WHERE genre ILIKE ${"%" + genre + "%"}
        ORDER BY popularity DESC NULLS LAST
        LIMIT ${limit}
      `
      return result as Song[]
    },
    songDatabase.filter((song) => song.genre.toLowerCase().includes(genre.toLowerCase())).slice(0, limit),
  )
}

export async function searchSongsByMetadata(
  genre?: string,
  mood?: string,
  tempo?: string,
  limit = 20,
): Promise<Song[]> {
  return executeWithFallback(
    async () => {
      // Build the query conditions
      const conditions = []
      const params = []

      if (genre) {
        conditions.push(`genre ILIKE $${params.length + 1}`)
        params.push(`%${genre}%`)
      }
      if (mood) {
        conditions.push(`mood ILIKE $${params.length + 1}`)
        params.push(`%${mood}%`)
      }
      if (tempo) {
        conditions.push(`tempo ILIKE $${params.length + 1}`)
        params.push(tempo)
      }

      // const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : ""

      // Use template literal with proper parameter substitution
      if (conditions.length === 0) {
        const result = await sql`
          SELECT * FROM songs 
          ORDER BY popularity DESC NULLS LAST 
          LIMIT ${limit}
        `
        return result as Song[]
      } else if (conditions.length === 1) {
        if (genre && !mood && !tempo) {
          const result = await sql`
            SELECT * FROM songs 
            WHERE genre ILIKE ${`%${genre}%`}
            ORDER BY popularity DESC NULLS LAST 
            LIMIT ${limit}
          `
          return result as Song[]
        } else if (mood && !genre && !tempo) {
          const result = await sql`
            SELECT * FROM songs 
            WHERE mood ILIKE ${`%${mood}%`}
            ORDER BY popularity DESC NULLS LAST 
            LIMIT ${limit}
          `
          return result as Song[]
        } else if (tempo && !genre && !mood) {
          const result = await sql`
            SELECT * FROM songs 
            WHERE tempo ILIKE ${`%${tempo}%`}
            ORDER BY popularity DESC NULLS LAST 
            LIMIT ${limit}
          `
          return result as Song[]
        }
      } else if (conditions.length === 2) {
        if (genre && mood && !tempo) {
          const result = await sql`
            SELECT * FROM songs 
            WHERE genre ILIKE ${`%${genre}%`} AND mood ILIKE ${`%${mood}%`}
            ORDER BY popularity DESC NULLS LAST 
            LIMIT ${limit}
          `
          return result as Song[]
        } else if (genre && tempo && !mood) {
          const result = await sql`
            SELECT * FROM songs 
            WHERE genre ILIKE ${`%${genre}%`} AND tempo ILIKE ${`%${tempo}%`}
            ORDER BY popularity DESC NULLS LAST 
            LIMIT ${limit}
          `
          return result as Song[]
        } else if (mood && tempo && !genre) {
          const result = await sql`
            SELECT * FROM songs 
            WHERE mood ILIKE ${`%${mood}%`} AND tempo ILIKE ${`%${tempo}%`}
            ORDER BY popularity DESC NULLS LAST 
            LIMIT ${limit}
          `
          return result as Song[]
        }
      } else if (conditions.length === 3) {
        const result = await sql`
          SELECT * FROM songs 
          WHERE genre ILIKE ${`%${genre}%`} AND mood ILIKE ${`%${mood}%`} AND tempo ILIKE ${`%${tempo}%`}
          ORDER BY popularity DESC NULLS LAST 
          LIMIT ${limit}
        `
        return result as Song[]
      }

      // Fallback to all songs if no conditions match
      const result = await sql`
        SELECT * FROM songs 
        ORDER BY popularity DESC NULLS LAST 
        LIMIT ${limit}
      `
      return result as Song[]
    },
    songDatabase
      .filter((song) => {
        const genreMatch = !genre || song.genre.toLowerCase().includes(genre.toLowerCase())
        const moodMatch = !mood || song.mood?.toLowerCase().includes(mood.toLowerCase())
        const tempoMatch = !tempo || song.tempo?.toLowerCase().includes(tempo.toLowerCase())
        return genreMatch && moodMatch && tempoMatch
      })
      .slice(0, limit),
  )
}

export async function getAllGenres(): Promise<string[]> {
  return executeWithFallback(async () => {
    const result = await sql`
        SELECT DISTINCT genre 
        FROM songs 
        WHERE genre IS NOT NULL AND genre != ''
        ORDER BY genre
      `
    return result.map((row: any) => row.genre).filter(Boolean)
  }, [...new Set(songDatabase.map((song) => song.genre))])
}

export async function getSongStats(): Promise<{
  totalSongs: number
  totalGenres: number
  totalArtists: number
}> {
  return executeWithFallback(
    async () => {
      const [songsResult, genresResult, artistsResult] = await Promise.all([
        sql`SELECT COUNT(*) as count FROM songs`,
        sql`SELECT COUNT(DISTINCT genre) as count FROM songs WHERE genre IS NOT NULL`,
        sql`SELECT COUNT(DISTINCT artist_name) as count FROM songs WHERE artist_name IS NOT NULL`,
      ])

      return {
        totalSongs: Number(songsResult[0]?.count || 0),
        totalGenres: Number(genresResult[0]?.count || 0),
        totalArtists: Number(artistsResult[0]?.count || 0),
      }
    },
    {
      totalSongs: songDatabase.length,
      totalGenres: new Set(songDatabase.map((s) => s.genre)).size,
      totalArtists: new Set(songDatabase.map((s) => s.artist_name)).size,
    },
  )
}
